import { faMusic, faPalette, faTerminal, faUser } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import styles from "../styles/Header.module.scss";
import Image from "next/image";
import { FC, ReactNode } from "react";
import Link from "next/link";

type LayoutProps = {
  children: ReactNode;
  pageId?: string;
};
export const Layout: FC<LayoutProps> = ({ children, pageId }) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav className={styles.nav}>
          <h4 className="title">Yoonsoo Kim</h4>
          <div className={styles.navButton}>
            <Link href={"/"} passHref={true}>
              <button id="navHome">
                <FontAwesomeIcon icon={faUser} />
                <span>Bio</span>
              </button>
            </Link>
            <Link href={"/dev"} passHref={true}>
              <button id="navDev">
                <FontAwesomeIcon icon={faTerminal} />
                <span>Dev</span>
              </button>
            </Link>
            <Link href={"/music"} passHref={true}>
              <button id="navMusic">
                <FontAwesomeIcon icon={faMusic} />
                <span>Music</span>
              </button>
            </Link>
            <Link href={"/graphic"}>
              <button id="navArt">
                <FontAwesomeIcon icon={faPalette} />
                <span>Graphic</span>
              </button>
            </Link>
          </div>
        </nav>
        <main id={pageId || ""} className={styles.main}>
          {children}
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};
